CC = g++
CFLAGS += -g -Wall -Werror

all: queue_test

queue_test:
	$(CC) $@.cpp --output $@

random-numbers:
	$(CC) $@.cpp --output $@

regular-expressions:
	$(CC) $@.cpp --output $@

map_test:
	$(CC) $@.cpp --output $@

clean:
	$(RM) queue_test  random-numbers regular-expressions map_test