CC = gcc
CFLAGS = -Wall -Werror

cont-stop:
	$(CC) $@.c --output $@

handles:
	$(CC) $@.c --output $@

proc-comm:
	$(CC) $@.c --output $@

send-arr:
	$(CC) $@.c --output $@

send-str:
	$(CC) $@.c --output $@

sigact:
	$(CC) $@.c --output $@

prntchld:
	$(CC) $@.c --output $@

clean:
	$(RM) cont-stop handles proc-comm send-arr send-str sigact prntchld

.PHONY: clean