BIN = bin

intro:
	gcc -o $(BIN)/intro 00-intro.c
waiting:
	gcc -o $(BIN)/waiting 01-waiting.c
ids:
	gcc -o $(BIN)/ids 02-ids.c
multifork:
	gcc -o $(BIN)/multifork 03-multifork.c

run-:

clean:
	rm bin/*

.PHONY: clean